force-app/main/default/objects/Field_History_Tracker__c/Field_History_Tracker__c.object-meta.xml
<CustomObject>
    <label>Field History Tracker</label>
    <nameField>
        <displayFormat>FHT-{000000}</displayFormat>
        <label>Field History Tracker Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field History Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_History_Tracker__c/fields/Batch_Status__c.field-meta.xml
<CustomField>
    <fullName>Batch_Status__c</fullName>
    <label>Batch Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/Sobject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Sobject_API_Name__c</fullName>
    <label>Sobject API Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/Sobject_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Sobject_Record_Id__c</fullName>
    <label>Sobject Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/recordTypes/Batch_Info.recordType-meta.xml
<RecordType>
    <fullName>Batch_Info</fullName>
    <active>true</active>
    <label>Batch Info</label>
</RecordType>

force-app/main/default/objects/Field_History_Tracker__c/recordTypes/tracker.recordType-meta.xml
<RecordType>
    <fullName>tracker</fullName>
    <active>true</active>
    <label>tracker</label>
</RecordType>

force-app/main/default/objects/Field_History_Tracker_Batch_Config__c/Field_History_Tracker_Batch_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field History Tracker Batch Config</label>
</CustomObject>

force-app/main/default/objects/Field_History_Tracker_Batch_Config__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <label>Batch Size</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ManageRecordHistoryTracking__mdt/ManageRecordHistoryTracking__mdt.object-meta.xml
<CustomObject>
    <label>Object History Tracking</label>
    <pluralLabel>Object History Trackings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ManageRecordHistoryTracking__mdt/fields/TrackedFieldName__c.field-meta.xml
<CustomField>
    <fullName>TrackedFieldName__c</fullName>
    <inlineHelpText>Comma separated list of fields api names which need to be tracked on history object.</inlineHelpText>
    <label>Tracked Fields List</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ManageRecordHistoryTracking__mdt/fields/Tracking_Object__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Object__c</fullName>
    <label>Tracking Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Object_History_Trackings</relationshipLabel>
    <relationshipName>Object_History_Trackings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/HistoryTrackingCreateRecordQueue.cls
public with sharing class HistoryTrackingCreateRecordQueue implements Queueable {
    private List<SobjectHistoryTrackingWrapper> recordsWrapper;

    public HistoryTrackingCreateRecordQueue(List<SobjectHistoryTrackingWrapper> recordsWrapper) {
        this.recordsWrapper = recordsWrapper;
    }

    public void execute(QueueableContext context) {
        insertHistoryRecordV2(recordsWrapper);
    }

    public static List<SobjectHistoryTrackingWrapper> insertHistoryRecordV2(List<SobjectHistoryTrackingWrapper> recordsWrapper) {
        Map<String, String> fieldsLabelMap = getFieldLabelList(String.valueOf(recordsWrapper[0].newRecordState.getSObjectType()));
        ManageRecordHistoryTracking__mdt configRecord = getConfigMetadataRec(String.valueOf(recordsWrapper[0].newRecordState.getSObjectType()));
        List<String> trackedFieldsList = configRecord.TrackedFieldName__c.split(',');
        List<sObject> sObjHistoryList = new List<sObject>(); 
        Map<String, Field_History_Tracker__c> fhtMap = new Map<String, Field_History_Tracker__c>();
        List<ContentVersion> filesToInsert = new List<ContentVersion>();

        //Map<String,Field_History_Tracker__c> recordsToCVMap = new Map<String,Field_History_Tracker__c>();
        for(SobjectHistoryTrackingWrapper ohtWrapper: recordsWrapper){
            if(ohtWrapper.oldRecordState != null){
                Field_History_Tracker__c fht = new Field_History_Tracker__c();
                fht.Sobject_API_Name__c = String.valueOf(ohtWrapper.newRecordState.getSObjectType());
                fht.Sobject_Record_Id__c = ohtWrapper.newRecordState.Id;
                System.debug(ohtWrapper.newRecordState.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName());
                fht.RecordTypeId = fht.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('tracker').getRecordTypeId();
                fhtMap.put(ohtWrapper.newRecordState.Id, fht);

                ContentVersion cvNewState = new Contentversion(); 
                cvNewState.Title = 'Record_New_State'; 
                cvNewState.PathOnClient = 'Record_New_State.json';
                cvNewState.Description = fht.Sobject_Record_Id__c;
                cvNewState.VersionData = Blob.valueOf(JSON.serialize(ohtWrapper.newRecordState));
                //insert cvNewState; // Save test json as file with header data linking to the app reference.
                filesToInsert.add(cvNewState);
                //recordsToCVMap.put(cvNewState.Title, fht);                

                ContentVersion cvOldState = new Contentversion(); 
                cvOldState.Title = 'Record_Old_State'; 
                cvOldState.Description = fht.Sobject_Record_Id__c;
                cvOldState.PathOnClient = 'Record_Old_State.json'; 
                cvOldState.VersionData = Blob.valueOf(JSON.serialize(ohtWrapper.oldRecordState));
                //insert cvOldState; // Save test json as file with header data linking to the app reference.
                filesToInsert.add(cvOldState);
                //recordsToCVMap.put(cvOldState.Title, fht);
            }
        }

        if(fhtMap.size() > 0) insert fhtMap.values();
        if(filesToInsert.size() > 0) insert filesToInsert;

        List<ContentVersion> cvList = [SELECT Id, ContentDocumentId,Description FROM ContentVersion WHERE Id IN :filesToInsert];
        List<ContentDocumentLink> cdlList = new List<ContentDocumentLink>();
        for(ContentVersion cv : cvList){
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.LinkedEntityId = fhtMap.get(cv.Description).Id;
            cdl.ContentDocumentId = cv.ContentDocumentId;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers';
            cdlList.add(cdl);
        }        
        if(cdlList.size() > 0) insert cdlList;

        checkAndExecuteBatch();

        return recordsWrapper;
    }


    public static void checkAndExecuteBatch(){
        
        //List<AsyncApexJob> aaJobs = [SELECT Id, ApexClassId, ApexClass.Name  FROM AsyncApexJob WHERE ApexClass.Name = 'FieldHistoryCreationBatch' AND CompletedDate = null];
        List<Field_History_Tracker__c> fhtList = [SELECT Id, Batch_Status__c, Name FROM Field_History_Tracker__c WHERE RecordType.DeveloperName = 'Batch_Info' AND Batch_Status__c = 'In-Progress'];
        if(fhtList.size() == 0) {
            Field_History_Tracker__c fht = new Field_History_Tracker__c();
            fht.Batch_Status__c = 'In-Progress';
            fht.RecordTypeId = Schema.SObjectType.Field_History_Tracker__c.getRecordTypeInfosByDeveloperName().get('Batch_Info').getRecordTypeId();
            insert fht;
            startHistoryTrackingBatch();
        }
        
    }

    public static void startHistoryTrackingBatch(){
        FieldHistoryCreationBatch fhcBatch = new FieldHistoryCreationBatch();
        Integer batchSize =  Field_History_Tracker_Batch_Config__c.getInstance().Batch_Size__c == null ? 10 : Integer.valueOf(Field_History_Tracker_Batch_Config__c.getInstance().Batch_Size__c);
        Database.executeBatch(fhcBatch,batchSize);
    }
    
    public static ManageRecordHistoryTracking__mdt getConfigMetadataRec(String objectName){
        if(!Test.isRunningTest()){
            ManageRecordHistoryTracking__mdt metadataRec = [SELECT DeveloperName, Tracking_Object__r.QualifiedApiName, TrackedFieldName__c
                FROM ManageRecordHistoryTracking__mdt WHERE Tracking_Object__r.QualifiedApiName = :objectName];
                return metadataRec; 
        }
        else{
            ManageRecordHistoryTracking__mdt metadataRec = new ManageRecordHistoryTracking__mdt();
            EntityDefinition ed = [SELECT Id FROM EntityDefinition WHERE QualifiedApiName = 'Account' LIMIT 1];
            metadataRec.DeveloperName = 'myName';
            metadataRec.Tracking_Object__c = 'Account';
            metadataRec.TrackedFieldName__c = 'Name,Email';
            return metadataRec;
        }
        
        
    }
    
    public static Map<String, String> getFieldLabelList(String sObjectName){
        Map<String, String> fieldList = new Map<String, String>();
        if(sObjectName != null){
            Map<String,SObjectField> fList = Schema.getGlobalDescribe().get(sObjectName).getDescribe().fields.getMap();
            for(String str: fList.keySet()){
                fieldList.put(str.toLowerCase(), fList.get(str).getDescribe().getLabel());                
            }
        }else{
            return null;
        }
        return fieldList;
    }
}